language: node_js
node_js:
  - 8.12.0
sudo: required
services:
  - docker
env:
  global:
    - CXX=g++-4.8
  matrix:
    - USE_SENTRY=1

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

before_install:
  - docker pull getsentry/sentry-cli

script:
  - npm install
  - NODE_ENV=production npm run build:dll
  - npm run build

before_deploy:
#  - bash deploy/sentry_release.sh
  - find dist/ -type f -name "*.map" -delete
  - zip -r dist.zip dist

deploy:
  provider: releases
  skip_cleanup: true
  api_key:
    secure: cUs72lPWFx+X1LGQx/HdLGrWc5TET54akk6kU4B1uQHKY4A/uCXreUbtMQl+5oxRfZIsAwiGR39xk1MjmuK3/gXfmcWkOZP3lZD2K2DBYvxzscsHo+tKfM+pk3oW4iV0xjCmDiuCVYCWN8L9mN1zGZC5pJAIDZvcpQZlvsoVzYKA6NAdN1O/trWtvyWvbSnKMB9DDXL+WsB5uRUYXURiomIANbvoKH0brBoFT0TQ8M89wvmnl36tdyDuvAqBAJMzQ0F/y/W4k+7wzj64U7G5BPqCN9kpZAeEOo+aI2BiYRPYS6mjKjPNwfw0bn4pvRv4B2H7hqzA7lrRAE4ry42lPZfCs+qKQg3J7MHU0oeGxPzweVP3nDCkvdMpFAn9i4l+zMONRGvuTKcHzv31TGoF+QXpmzozqHeDn4sUSb5xU9bcv1ErNHd+HnCzoYpxOzhOREVR16cPi3aOUJcGWRBOkA60rZsqMhKVnPn8NCq9+Es1ifjiCSSyn1zoWilmrEiGq8fo1MiRL22oWR2YHAVxBHrntM0w74QxLSXhFAO0W6xILJX2SuMQNnOqK6QWWeg18Ut1O62lv38F02D3b8CUnyxjPoEspP2ni8J69Jr4o9yl1m9bPAJaLRz2/yCpdB31RAzArFBfmrY1DTAr8fstB2PXFLozsT0S7OhNkRdlElU=
  file: dist.zip
  on:
    repo: Harry-zklcdc/OJ
    all_branches: true
    tags: true
